# Generated by Django 3.2.9 on 2021-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_post_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
